name: second

services:
  master:
    container_name: master
    image: serhii714/ds:iter2
    ports:
      - 8000:80
    networks:
      - replicated_log
    cap_add:
      - NET_ADMIN
    command: ["master.py"]

  slave:
    scale: 3
    image: serhii714/ds:iter2
    ports:
      - 8001-9000:80
    networks:
      - replicated_log
    cap_add:
      - NET_ADMIN
    command: ["slave.py"]

networks:
  replicated_log:
