name: second

services:
  master:
    container_name: master
    image: serhii714/ds:iter2
    ports:
      - 8000:80
    networks:
      - replicated_log
    cap_add:
      - NET_ADMIN
    volumes:
      - ./app:/app
    command: ["master.py", "--debug"]

  slave:
    scale: 3
    image: serhii714/ds:iter2
    ports:
      - 8001-8100:80
    networks:
      - replicated_log
    cap_add:
      - NET_ADMIN
    volumes:
      - ./app:/app
    command: ["slave.py", "--debug"]

networks:
  replicated_log:
